
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "johnny5@gmail.com",
    "password": "test6"
}

### GET USER BY ID
GET http://localhost:3000/auth/1

### LOGIN TESTING
POST http://localhost:3000/auth/signin
Content-Type: : application/json

{
    "email": "test@gmail.com",
    "password": "test1"
}



